version: '3'

services:
  app:
    build: ./
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    networks:
      - vegenet
volumes:
  node_modules:
networks:
  vegenet:
    external: true
    name: vegevery_server_vegenet
